# Generated by Django 5.1.6 on 2025-03-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='codigo_barras',
            new_name='codigobarra',
        ),
    ]
